config/routes.rb
Rails.application.routes.draw do
  get '/shop' => 'storefront#index'
  get '/about' => 'storefront#about'
  get '/home' => 'storefront#home'

  devise_for :users
namespace :admin do
  resources :products
  resources :brands
  resources :categories
end

resources :orders, only: [:new, :create, :show]

resources :line_items, only: [:create, :destroy, :update]

resource :cart, only:[:edit, :update, :destroy]

  root 'storefront#home'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def subtotal
    #this is slow, should use sql to do sum for you
    #line_items.to_a.sum{ |item| item.total}

    #use sql
    #("SUM(quantity * price) AS sum") does the sum
    #[0] gets the first one in table/all values
    # .sum is returning the sum field of [0]
    line_items.select("SUM(quantity * price) AS sum")[0].sum
  end

  def add_product(product_id)
    product = Product.find(product_id)

    # Find out if this product is already in cart. If not, current_item will be nil
    current_item = line_items.find_by(product_id: product_id)

    # If current_item does exist in cart, increase the quantity. If not, build the new line item.
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product: product, price: product.current_price)
    end
    current_item
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  #calls the module CurrentCart - need to use exact name of module
  include CurrentCart

  #pulls this action from ???

  before_action :set_cart
  def edit
  end

  def update
  end

  def destroy
    if @cart.destroy
      session[:cart_id] = nil
      flash[:notice] = "Cart successfully deleted"
      redirect_to shop_url
    else
      flash[:alert] = "Could not delete cart."
      redirect_to edit_cart_url
    end
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th colspan="2">Product</th>
      <th>Quantity</th>
      <th>Unit Price</th>
      <th>Total Price</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% cart.line_items.each do |item| %>
    <tr>
      <td><%= image_tag item.product.avatar.url(:thumb), class:"img-responsive img-thumbnail" %></td>
      <td><%= item.product.name %></td>
      <td>
          <%= simple_form_for(item, html: {class: 'form-inline'}) do |item_fields| %>
            <%= item_fields.input :quantity, label: false %>
            <%= item_fields.button :submit, "Save" %>
          <% end %>
      </td>
      <td><%= number_to_currency item.price %></td>
      <td><%= number_to_currency item.total %></td>

      <td><%= link_to fa_icon('trash', text: "delete"), line_item_path(item), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<h3>Order Subtotal: <%= number_to_currency cart.subtotal %></h3>

app/views/carts/edit.html.erb
<h1>Your Shopping Cart</h1>

<%= render @cart %>

<small>p.s. This isn't an actual store, but, a lesson to learn RoR.</small>
<div class="pull-right">
<%= link_to "continue shopping", shop_path, class:"btn btn-warning" %>
<%= link_to "empty cart", @cart, method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-danger" %>
<%= link_to fa_icon("money", text:"checkout"), new_order_path, class:"btn btn-success" %>
</div>
<div>
 <br><br>
</div>