config/routes.rb
Rails.application.routes.draw do
  get '/shop' => 'storefront#index'
  get '/about' => 'storefront#about'
  get '/home' => 'storefront#home'

  devise_for :users
namespace :admin do
  resources :products
  resources :brands
  resources :categories
end

resources :orders, only: [:new, :create, :show]

resources :line_items, only: [:create, :destroy, :update]

resource :cart, only:[:edit, :update, :destroy]

  root 'storefront#home'

end

app/models/category.rb
class Category < ActiveRecord::Base
  #validation - make sure no repeats, require name as they are seeded and can then use titleize in index.html
  has_many :products
  validates_uniqueness_of :name
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.order(:name)
    @skip_footer = true
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @skip_footer = true
  end

  # GET /categories/new
  def new
    @category = Category.new
    @skip_footer = true
  end

  # GET /categories/1/edit
  def edit
    @skip_footer = true
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)
    @skip_footer = true

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_category_url(@category), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    @skip_footer = true
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @skip_footer = true
    @category.destroy
    respond_to do |format|
      format.html { redirect_to admin_categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<div class="container">
<div class="row">
<div class="col-sm-2"></div>
<div class="col-sm-8 well">
<%= simple_form_for([:admin, @category]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
<br>
</div>
<div class="col-sm-2"></div>
</div>
</div>

app/views/admin/categories/edit.html.erb
<h1>Edit Category</h1>

<%= link_to fa_icon('eye', text: "view"), admin_category_path(@category) %> |
<%= link_to fa_icon('arrow-left ', text: "back"), admin_categories_path %>

<%= render 'form' %>

app/views/admin/categories/index.html.erb
<h1>Categories</h1>
<%= link_to fa_icon('plus', text: "Add New Category"), new_admin_category_path, class:"btn btn-info pull-right" %>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name.titleize %></td>
        <td><%= link_to fa_icon('eye', text: "view"), admin_category_path(category) %></td>
        <td><%= link_to  fa_icon('pencil', text: "edit"), edit_admin_category_path(category) %></td>
        <td><%= link_to fa_icon('trash', text: "delete"), admin_category_path(category), method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br>

app/views/admin/categories/new.html.erb
<h1>New Category</h1>
<%= link_to fa_icon('arrow-left ', text: "back"), admin_categories_path %>

<%= render 'form' %>

app/views/admin/categories/show.html.erb
<div class="container">
<div class="row">
<br>
<div class="col-sm-2"></div>
<div class="col-sm-8 well">


<h2>Category Info</h2>
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to fa_icon('pencil', text: "edit"), edit_admin_category_path(@category) %> |
<%= link_to fa_icon('arrow-left ', text: "back"), admin_categories_path %>
<br>
</div>
<div class="col-sm-2"></div>
</div>
</div>